<?php

namespace AppBundle\Repository;

/**
 * TweetRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourne les 10 derniers tweets ajoutés en base de données.
     *
     * @param int $maxResults
     *
     * @return Tweet[]
     */
    public function getLastTweets($maxResults = 10)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->setMaxResults($maxResults)
            ->orderBy('t.createdAt', 'DESC')
            ->getQuery()
            ->getResult();

        return $qb;
    }

    /**
     * Retourne un tweet par id.
     *
     * @param $id
     *
     * @return mixed
     */
    public function getTweet($id)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();

        return $qb;
    }
}
