# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    app.tweet_manager:
        class: AppBundle\Manager\TweetManager
        arguments :
           - "@=service('doctrine').getManager()"
           - "%app.tweet.nb_last%"

    app.email_messenger:
        class: AppBundle\Messenger\EmailMessenger
        arguments :
        - "@mailer"